info:
  name: content-center11
spring:
  application:
    name: content-center11
#  zipkin:
#    base-url: http://localhost:9411/
#    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/content_center?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.111.64.183:8848
    sentinel:
      transport:
        dashboard: localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

server:
  port: 8081
#ribbon:
#  eager-load:
#    clients: user-center
#    enabled: true

logging:
  level:
    # feign的日志系统是建立在SpringBoot基础上的，此处一定要是debug，否则不会打印,指定到包下指定的类
    com.soft1851.spring.cloud.feignclient.UserCenterFeignClient: debug
feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
rocketmq:
  name-server: 47.111.64.183:9876
  producer:
    # 必须指定group
    group: test-group
jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  expire-time-in-second: 1209600