info:
  name: content-center
spring:
  application:
    name: content-center
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://106.15.234.237:3306/content_center?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.111.64.183:8848

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

server:
  port: 8080
#ribbon:
#  eager-load:
#    clients: user-center
#    enabled: true

logging:
  level:
    # feign的日志系统是建立在SpringBoot基础上的，此处一定要是debug，否则不会打印,指定到包下指定的类
    com.soft1851.spring.cloud.feignclient.UserCenterFeignClient: debug
feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
