info:
  name: content-center
spring:
  application:
    name: content-center
  datasource:
    url: jdbc:mysql://106.15.234.237:3306/content_center?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.111.64.183:8848

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
server:
  port: 8080
ribbon:
  eager-load:
    clients: user-center
    enabled: true
feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
  httpclient:
    # 让fegin使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
