info:
  name: user-center11
spring:
#  zipkin:
#    base-url: http://localhost:9411/
#    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: user-center11
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.111.64.183:8848
        metadata:
          instance: user
          version: 1.2
server:
  port: 8006
target:
  string:
    target:
      nihao
rocketmq:
  name-server: 47.111.64.183:9876

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  expire-time-in-second: 1209600

#logging:
#  level:
#    com.alibaba.nacos: error
#    org.springframework.cloud.sleuth: debug
