info:
  name: user-center
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.60.46:8848
        metadata:
          instance: user
          version: 1.2
server:
  port: 8006
target:
  string:
    target:
      nihao
rocketmq:
  name-server: 47.111.64.183:9876